insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values(101,'HCL' ,700.25);

insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values(102, 'Infosys' ,900.25);

insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values(103, 'BHEL' ,40.35);

insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values(104, 'Inueron' ,70.25);